name: build

on:
  workflow_dispatch:
  
jobs:
  build_msvc:
    uses: ./.github/workflows/msvc.yml
	  
  deploy:
    runs-on: ubuntu-laster
    needs: [build_msvc]
    steps:
      - name: "echo file"
        run: |
          echo "${{ build_msvc.output.setup_file }}"
          cat ${{ build_msvc.output.setup_file }}
