name: build

env:
  artifact_path: artifact_path
  DEBIAN_VERSION: 0.3.0

on: 
  push:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Display structure of downloaded files
        run: |
          RPM_VERSION=${DEBIAN_VERSION//-/\~}
          echo $RPM_VERSION
          
