name: build

on: [push]
  
jobs:
  build_msvc:
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ./.github/workflows/msvc.yml
	  
  deploy:
    runs-on: ubuntu-laster
    needs: [build_msvc]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: "echo file"
        run: |
          echo "${{ build_msvc.output.setup_file }}"
          cat ${{ build_msvc.output.setup_file }}
