name: build

on:

jobs:
  build_msvc:
    steps:
      - uses: ./.github/workflows/msvc.yml
	  
  deploy:
    needs: [build_msvc]
    steps:
      - run: |
        echo "${{ build_msvc.output.setup_file }}"
        cat ${{ build_msvc.output.setup_file }}