name: build_ubuntu

on:
  workflow_call:
    outputs:
      name:
        description: "The artifact name"
        value: ${{ jobs.build_ubuntu.outputs.name }}

env:
  artifact_name: build_ubuntu

jobs:
  build_ubuntu:
    strategy:
      matrix:
        os: [Ubuntu-22.04, Ubuntu-20.04]

    runs-on: ${{matrix.os}}
    
    env:
      artifact_name: build_msvc

    # Map the job outputs to step outputs
    outputs:
      name: ${{ env.artifact_name }}
  
    steps:

      - name: echo
        run: |
          echo "build ${{matrix.os}}" > build2_${{matrix.os}}.txt

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.artifact_name }}
          path: build2_${{matrix.os}}.txt
