name: ubuntu

on: [push]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  build:
    strategy:
      matrix:
        os: [Ubuntu-20.04]
        # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
        BUILD_TYPE: [Release]

    runs-on: ${{matrix.os}}
    env:
      BUILD_TYPE:  ${{ matrix.BUILD_TYPE }}
      SOURCE_DIR:  ${{github.workspace}}/3th_2021_12_04/source
      TOOSL_DIR:   ${{github.workspace}}/3th_2021_12_04/tools
      INSTALL_DIR: ${{github.workspace}}/3th_2021_12_04/install
      RabbitRemoteControl_VERION: 0.0.9
      
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    
    - name: update xml file
      if: ${{ matrix.BUILD_TYPE == 'Release' }}
      working-directory: ${{github.workspace}}
      run: |
        sudo apt-get install -y -qq xvfb xpra
        sudo Xvfb :99 -ac &
        export DISPLAY=:99.0
        echo "Install rabbit remote control ..."

